### ISSUE TITLE
赶走偷吃的鸡出现问题

### ISSUE THREAD

**Issue by baocq2019** [TonyJiangWJ/Ant-Manor#1]
左边的鸡无法赶走，直接赶走右边就结束了进程。另外大神能把加速卡的选项也做进去吗，感谢

**Comment by TonyJiangWJ** [comment]
加速卡加进去了。无法赶走的话最好提供一下日志 我自己测试时没问题的  也许是分辨率不同点击的位置有问题

**Comment by baocq2019** [comment]
还是同样的问题，分辨率已经修改，我用的是2340*1080，开启脚本时，正加速喂饲料阶段，没有偷吃鸡，但脚本检测到左边有小偷鸡，然后进入使用加速卡，在这个界面几秒后，停止了脚本。
[http://chuantu.xyz/t6/703/1575209696x1031866013.jpg](url)
[http://chuantu.xyz/t6/703/1575209726x1033347913.jpg](url)

**Comment by TonyJiangWJ** [comment]
可能是你的鸡的装扮问题 黑色识别成野鸡了 你把它衣服脱了

**Comment by baocq2019** [comment]
http://chuantu.xyz/t6/703/1575210275x1031866013.jpg

**Comment by TonyJiangWJ** [comment]
识别区域的问题我改掉了，你先更新一下代码。
然后你给的这个截图 十点零二分的 不是脱了衣服后的吧？

**Comment by baocq2019** [comment]
http://chuantu.xyz/t6/703/1575282426x3030586988.png
感谢大神的持续更新，最新日志记录，启动前状态：小鸡衣服已脱，小鸡没有喂食。启动脚本：喂食和检测正常，使用加速卡正常。但是在使用加速卡之后。检测日志显示未使用加速卡，然后20分钟后重启脚本检测。

**Comment by TonyJiangWJ** [comment]
图片链接你可以按下面的格式填写 免得要点过去
```markdown
![图片文字描述,比如原始链接](http://chuantu.xyz/t6/703/1575210275x1031866013.jpg)
```
![http://chuantu.xyz/t6/703/1575210275x1031866013.jpg](http://chuantu.xyz/t6/703/1575209696x1031866013.jpg)

从日志看 应该是识别区域的问题 x:480 y:1646这个位置 你得看一下你手机上  小鸡加速后左手拿的饲料位置 y值是不是远小于1646 查看方式 开发者模式 指针位置。找到它然后修改这里的值 
```javascript
/core/AntManorRunner.js
SPEED_CHECK_REGION: [480, 1520, 10, 10],
```
这个1520是在我手机上的位置，你要先确定自己的y值 然后这个1520最后会乘以`const heightRate = HEIGHT / 2160`的，也就是最终是`1520*heightRate`. 你要做的就是得到你的位置比如Y0,将这个1520修改成`Y0/heightRate`即可 
```
// 比如得到Y0是1600 
// 1520改成1600/(2340/2160)=1476.9
SPEED_CHECK_REGION: [480, 1477, 10, 10],
```

**Comment by baocq2019** [comment]
关于加速卡检测区域，已对照修改好了，暂时没出现问题，但是检测小偷鸡我看到用的是白色  THIEF_COLOR: '#000000', 如果小偷鸡是带装扮的就检测失败，
![如下图中左边小偷鸡检测不到](http://chuantu.xyz/t6/703/1575339957x1033347913.jpg)

另外还有脚本的重启时间问题。本次测试，测试情况：已喂食并使用加速卡，也赶过小偷鸡，，脚本连续几次设定在5分钟后重启，约3-4次重启执行后，再之后的重启设定为200分钟后重启。但此时小鸡饲料已只剩下90分钟，中间有较长的真空期。

请问能否根据当前饲料剩余时间去设定下次启动脚本时间。
这需要建立在已经赶过一次小偷鸡的前提上，正常喂食，小偷鸡只会在半个小时之内来一次，之后便不会再出现，除非有人用蹭饭卡，但因为脚本频繁重启可能手机耗电会明显增加，所以这里提出这个建议，请问大神能否实现，在使用加速卡喂食后，半个小时后启动脚本，【目前测试过的普遍小偷鸡来的时间都在20-30分钟，此处被偷吃的饲料可以忽略不计】，在赶走小偷鸡之后，根据饲料剩余时间设定下一次脚本启动时间。

【再次鸣谢大神持续维护】

**Comment by TonyJiangWJ** [comment]
- `#000000` 是黑色哦
- 关于倒计时的 我测试了是没问题的除非你自己手动操作过或者没有更新到最新版。
- 目前的逻辑是喂完等20分钟 开始`5分钟的循环` `5次` 或者 `找到小偷鸡`，然后找到小鸡会根据实际经过时间计算一个`等待时间`+`5分钟的安全期`，5次之后没有野鸡则等待260分钟（使用了加速卡则再减去60）
- 然后饲料剩余时间除非OCR 单纯通过控件没法获取的 所以就按上述逻辑了
- 没有其他问题 我close了
- 图片看不见是你的图床有效期太短了 比如这个可能今天还在 明天就没了
  ![http://chuantu.xyz/t6/703/1575341066x1033347913.jpg](http://chuantu.xyz/t6/703/1575341066x1033347913.jpg)
