### ISSUE TITLE
分辨率1280x720参数

### ISSUE THREAD

**Issue by williamglasgow** [TonyJiangWJ/Ant-Manor#10]
我的设备是红米4x和红米note5a，屏幕尺寸分别是5寸和5.5寸，分辨率都是1280x720，下面是我调试后修改的参数，供大家参考。
（颜色我只改了一个，把揍走小鸡改成了赶走，所以颜色从红色的锤头改成了和饲料一样的黄色，经测试有效）
（校验是否存在饲料有点问题，不知道是程序原因还是区域设置问题，有饲料有时能检测到，有时却检测不到；位置的话，10x10的区域我已经设置在贴在盆上缘的饲料中点了）

>  CHECK_APP_COLOR: '#f1381a', 
  CHECK_FRIENDS_COLOR: '#429beb', 
  THIEF_COLOR: '#000000',
  PUNCH_COLOR: '#ffcf00',
  OUT_COLOR: '#c37a3e',
  OUT_IN_FRIENDS_COLOR: '#e9ca02',
  DISMISS_COLOR: '#f9622f',
  FOOD_COLOR: '#ffcf00',
  SPEED_CHECK_COLOR: '#ffd000',
  OFFSET: 0, 
  CHECK_APP_REGION: [193, 197, 50, 50],
  CHECK_FRIENDS_REGION: [35, 308, 40, 40], 
  OUT_REGION: [266, 650, 40, 40], 
  OUT_IN_FRIENDS_REGION_RIGHT: [546, 754, 40, 40], 
  OUT_IN_FRIENDS_REGION_LEFT: [241, 754, 40, 40],  
  LEFT_THIEF_REGION: [218, 852, 10, 10], 
  LEFT_PUNCH_REGION: [152, 774, 66, 66], 
  RIGHT_THIEF_REGION: [590, 845, 10, 10], 
  RIGHT_PUNCH_REGION: [445, 774, 66, 66],
  DISMISS_REGION: [297, 1250, 10, 10],
  FOOD_REGION: [560, 970, 10, 10], 
  SPEED_CHECK_REGION: [315, 865, 10, 10],
  // 喂饲料按钮的位置  FEED_POSITION: {    x: 609,    y: 1170  },
  // 道具包按钮的位置  TOOL_POSITION: {    x: 638,//638    y: 465  },
  // 道具包中加速卡按钮的位置  SPEED_CARD_POSITION: {    x: 130,    y: 815  },
  // 确认按钮的位置  CONFIRM_POSITON: {    x: 475,     y: 831  }

【再次鸣谢作者！】

**Comment by TonyJiangWJ** [comment]
可以运行 `test/全局悬浮窗显示-音量上键关闭.js` 校验一下你的配置信息

**Comment by williamglasgow** [comment]
哇，这加上新功能可太好了，更方便大家自己设置了，感谢作者！！！
另外目前设置是这个样子，当前时间运行还是会显示小鸡没在吃饭，请问我这个判断食盆区域的设置应该如何修改一下？

![Screenshot_2020-05-06-11-48-43-929_com eg android](https://user-images.githubusercontent.com/58156677/81136987-b64fcd80-8f8f-11ea-9ad9-d84f0689d90a.jpg)

**Comment by TonyJiangWJ** [comment]
试试再往右移动10像素 ` FOOD_REGION: [570, 970, 10, 10] `

**Comment by williamglasgow** [comment]
改了之后运行了几次还是显示小鸡没饭吃（饲料还剩40min的），不太清楚什么原因。但目前从我有限的测试中总结得出的规律就是，从刚喂食到蹭饭小鸡来之前这段时间运行都没问题，都会检测到有饭吃；但在赶走蹭饭小鸡之后，无论还剩3.5h还是不到1h，都提示小鸡没吃饭。
仅供你调试参考

**Comment by TonyJiangWJ** [comment]
不行的话你把饲料判断区域 `FOOD_REGION `改为小鸡左手饲料的区域大概是 `[370, 865, 10, 10]`，颜色 `FOOD_COLOR` 也改成 `#ffd000` 具体值你看着调试吧
我自己用没遇到你这样的问题

**Comment by williamglasgow** [comment]
哈哈这太机智了，那应该就没问题了，另外顺带提个小问题：
manor运行期间音量上键无法停止运行了（这两个版本才出现的），音量下键延迟5min是正常的。forest都是正常的。不知道是有意为之还是啥。供参考。

**Comment by TonyJiangWJ** [comment]
这个我取消掉了，因为停止的话 会忘记再次启动，小鸡就没饭吃了，五分钟后启动则不会怕忘记。
森林的话停止了也影响不大

**Comment by williamglasgow** [comment]
确实是这样哈哈，那没问题了，十分感谢！！

**Comment by williamglasgow** [comment]
蚂蚁庄园更新了，正好比较有空调试了一下1280x720的参数，特来更新一下，再次感谢作者的工作，包括主程序和辅助调参的工具都做得非常棒！

>   OFFSET: 0,  // 默认配置为支持2160*1080分辨率，其他异形屏一般可以尝试仅仅修改该偏移量, 如果不行就修改具体区域的配置吧
  CHECK_APP_REGION: [200, 180, 30, 30],             // 校验是否成功打开蚂蚁庄园的区域，左上角❤️的区域[310, 250, 20, 20]
  CHECK_FRIENDS_REGION: [50, 308, 40, 40],         // 校验是否在好友首页的区域  左上角 发消息蓝色的区域 [120, 490, 10, 10]
  OUT_REGION: [266, 650, 40, 40],                  // 校验小鸡是否出门，牌子的区域[400, 1200, 50, 50]
  OUT_IN_FRIENDS_REGION_RIGHT: [237, 692, 40, 40], // 校验小鸡在好友家，左边的区域[800, 1350, 50, 50]
  OUT_IN_FRIENDS_REGION_LEFT: [540, 692, 40, 40],  // 校验小鸡在好友家，右边的区域[340, 1350, 40, 40]
  LEFT_THIEF_REGION: [209, 806, 10, 10],           // 校验来自家偷吃的小鸡，左边的区域
  LEFT_PUNCH_REGION: [138, 680, 66, 66],         // 校验左边拳头的区域[500, 1350, 100, 100]
  RIGHT_THIEF_REGION: [561, 806, 10, 10],          // 校验来自家偷吃的小鸡，右边的区域[930, 1510, 10, 10],
  RIGHT_PUNCH_REGION: [438, 680, 66, 66],        // 校验右边拳头的区域[980, 1350, 100, 100]
  DISMISS_REGION: [652, 112, 10, 10],              // 校验关闭按钮的区域 [450, 1890, 10, 10],
  FOOD_REGION: [370, 830, 10, 10],         //570 970        // 校验食盆的区域，主要校验是否存在饲料[850, 1700, 10, 10]
  SPEED_CHECK_REGION: [320, 816, 10, 10],          // 校验是否成功使用加速卡的区域，小鸡右手拿饲料的位置 [464, 1495, 10, 10]
  // 喂饲料按钮的位置  
FEED_POSITION: {    x: 609,    y: 1170  },
  // 道具包按钮的位置  
TOOL_POSITION: {    x: 640,    y: 463  },
  // 道具包中加速卡按钮的位置  
SPEED_CARD_POSITION: {    x: 126,    y: 820  },
  // 确认按钮的位置  
CONFIRM_POSITON: {    x: 457,    y: 813  }

**Comment by williamglasgow** [comment]
蚂蚁庄园更新了，正好比较有空调试了一下1280x720的参数，特来更新一下，再次感谢作者的工作，包括主程序和辅助调参的工具都做得非常棒！

> OFFSET: 0,
CHECK_APP_REGION: [200, 180, 30, 30], 
CHECK_FRIENDS_REGION: [50, 308, 40, 40], 
OUT_REGION: [266, 650, 40, 40], 
OUT_IN_FRIENDS_REGION_RIGHT: [237, 692, 40, 40], 
OUT_IN_FRIENDS_REGION_LEFT: [540, 692, 40, 40], 
LEFT_THIEF_REGION: [209, 806, 10, 10], 
LEFT_PUNCH_REGION: [138, 680, 66, 66], 
RIGHT_THIEF_REGION: [561, 806, 10, 10], 
RIGHT_PUNCH_REGION: [438, 680, 66, 66], 
DISMISS_REGION: [652, 112, 10, 10], 
FOOD_REGION: [370, 830, 10, 10], 
SPEED_CHECK_REGION: [320, 816, 10, 10], 
// 喂饲料按钮的位置
FEED_POSITION: { x: 609, y: 1170 },
// 道具包按钮的位置
TOOL_POSITION: { x: 640, y: 463 },
// 道具包中加速卡按钮的位置
SPEED_CARD_POSITION: { x: 126, y: 820 },
// 确认按钮的位置
CONFIRM_POSITON: { x: 457, y: 813 }
