### ISSUE TITLE
能够改成自适应不同分辨率的屏幕

### ISSUE THREAD

**Issue by tagaga** [TonyJiangWJ/Ant-Manor#11]
我的手机一加7Pro ，1440*3120的分辨率，改了一下发现还是不行，理论上检测不同手机分辨率自适应是可以的，老大你想想办法吧，谢谢

**Comment by TonyJiangWJ** [comment]
抱歉，完全基于图像分析的，只能手动配置。
已经给了工具方便你自行配置了，依旧不会，那我也无能为力。
