### ISSUE TITLE
蚂蚁庄园更新后bug

### ISSUE THREAD

**Issue by baocq2019** [TonyJiangWJ/Ant-Manor#12]
支付宝为最新版本
AutoJS 4.1.0Alpha5
Ant-manor v1.0.4.6.1

已经对应更新core中AntManorRunner的各项位置
1.脚本检测悬浮窗成功后，执行程序时的原先“绿字”消失
2.左侧小偷鸡检测成功并赶走
  右侧小偷鸡检测，点击后，不点拳按钮，脚本退出
  例：日志末尾截图如下：
http://chuantu.xyz/t6/737/1590756061x1700339730.jpg

望大佬指点
（区域设置right punch region等已校对过）

**Comment by TonyJiangWJ** [comment]
图片过期了，直接上传github就行了呀 这些图床啥都不是，github编辑框底下不是有个 `Attach files ...` 通过这个上传就行了 
示例如下：
![im_crying](https://user-images.githubusercontent.com/11325805/83469296-e1a3da80-a4b1-11ea-93ca-5cf2073b7837.png)

**Comment by baocq2019** [comment]
已经找到了，检测右侧拳超出区域，修改范围后就可以了，感谢😁
