### ISSUE TITLE
[BUG] 导入模块：[CommonFunction]失败，请检查代码

### ISSUE THREAD

**Issue by PLQin** [TonyJiangWJ/Ant-Manor#13]
## \# 问题描述

❀ 启用 `main.js` 报错： `导入模块：[CommonFunction]失败，请检查代码`  
❀ 启用 `config.js` 报错：  
```
函数importClass必须与一个类一起调用;改为使用"[JavaPackage com.stardust.autojs.ScriptEngineService]". (<init>#14)
    函数importClass必须与一个类一起调用;改为使用"[JavaPackage com.stardust.autojs.ScriptEngineService]".
    at <init>:14:0
    at file:/storage/emulated/0/脚本/Ant-Manor/lib/prototype/CommonFunction.js:32:0
    at _load (file:///android_asset/modules/jvm-npm.js:60:0)
    at /storage/emulated/0/脚本/Ant-Manor/config.js:101:0
```  

## \# 环境

❀ OPPO R15  
❀ Android 9
❀ Auto.js Pro 8.00-5

## \# 其它

针对  `main.js` 报错 :  
将目录 `Ant-Manor\lib\prototype` 下的 `CommonFunction.js` 复制一份到 目录 `Ant-Manor\lib` , 仍然无非解决异常, 且异常信息仍然是  `导入模块：[CommonFunction]失败，请检查代码`

**Comment by PLQin** [comment]
## \# 后续

#### \# ❀ 启用 main.js 报错： 导入模块：[CommonFunction]失败，请检查代码

替换 `singletonRequire` ,例如 : 
将 `let runningQueueDispatcher = singletonRequire('RunningQueueDispatcher')` 之类的代码更改为`let runningQueueDispatcher = require('./lib/prototype/RunningQueueDispatcher.js')`


#### \# ❀ 启用 config.js 报错

见 : https://github.com/TonyJiangWJ/Ant-Forest/issues/36

**Comment by TonyJiangWJ** [comment]
你这个先试试强制重启AutoJS软件 或者直接重启手机
