### ISSUE TITLE
RUNNING_PACKAGE is not define

### ISSUE THREAD

**Issue by dlinkqu** [TonyJiangWJ/Ant-Manor#14]
运行一次发现不能正常结束，查看日志发现报错：
RUNNING_PACKAGE is not define

grep了一下整个项目：

./lib/prototype/CommonFunction.js:401:    let runtimeStorages = storages.create(**RUNNING_PACKAGE**)

这里是否应该改成：

let runtimeStorages = storages.create(**RUNTIME_STORAGE**)

我自己手动改了之后能正常结束，不知道会不会影响其他功能。

**Comment by baocq2019** [comment]
出现同上问题，修改后还是会报错，RUNNING_STORAGE is not define。请大佬看看。

**Comment by TonyJiangWJ** [comment]
历史遗留代码 忘了改了

**Comment by dlinkqu** [comment]
> 出现同上问题，修改后还是会报错，RUNNING_STORAGE is not define。请大佬看看。

不是 **RUNNING_STORAGE**   是 **RUNTIME_STORAGE**
