### ISSUE TITLE
华为mate30（1080*2340）无法解锁屏幕

### ISSUE THREAD

**Issue by youm1ng** [TonyJiangWJ/Ant-Manor#16]
华为mate30（1080*2340），已经在config里输入了屏幕解锁密码，但软件无法解锁屏幕，且无法自动点击“立即开始”，如何解决？蚂蚁森林脚本没有这个问题。
![Screenshot_20200721_103929_com android systemui](https://user-images.githubusercontent.com/68574463/88006755-fe1dd400-cb3e-11ea-8a04-5c6eec9bffca.jpg)

**Comment by TonyJiangWJ** [comment]
main.js 第十行加一句 config.request_capture_permission=true

解锁的话代码和森林是同样的，你看一下是不是森林做了自定义扩展，或者直接把森林里面的Unlock.js复制过来

**Comment by youm1ng** [comment]
谢谢，问题已解决
