### ISSUE TITLE
能否增加识别喂食剩余时间

### ISSUE THREAD

**Issue by dlinkqu** [TonyJiangWJ/Ant-Manor#17]
不知道能否增加识别喂食剩余时间，别家小鸡来偷吃只在喂食后半小时内发生。且可以在驱赶小鸡后等待识别出来剩余喂食时间；
现在脚本会在自己驱赶小鸡后，不停的5分钟循环检测是否有小鸡偷吃。

**Comment by youm1ng** [comment]
是可以的，大概是你设置的问题吧。

**Comment by TonyJiangWJ** [comment]
已完成 更新到最新版 并配置识别区域
