### ISSUE TITLE
无法自动点击立即开始

### ISSUE THREAD

**Issue by unx123475** [TonyJiangWJ/Ant-Manor#18]
你好作者，我现在就是开始运行之后就会一直停留在授权截屏界面直到我手动点击授权，这个正常吗？因为我用的蚂蚁森林程序倒是可以自动点击授权。

**Comment by TonyJiangWJ** [comment]
额 应该是不正常 不过我已经点了记住了 所以自己也没去调试过，你试试最新版能不能自动点击吧

**Comment by unx123475** [comment]
可以了，辛苦了作者，谢谢！
