### ISSUE TITLE
分辨率2340*1080参数

### ISSUE THREAD

**Issue by baocq2019** [TonyJiangWJ/Ant-Manor#2]
机型Redmi K20 pro 分辨率2340*1080，测试部分颜色及区域修改如下：

  CHECK_APP_COLOR: '#f1381a',
  CHECK_FRIENDS_COLOR: '#52adff',
  THIEF_COLOR: '#000000',
  PUNCH_COLOR: '#f35458',
  OUT_COLOR: '#c27a3f',
  OUT_IN_FRIENDS_COLOR: '#f4d81d',
  DISMISS_COLOR: '#f9622f',
  FOOD_COLOR: '#ffcf00',
  SPEED_CHECK_COLOR: '#ffd000',

  CHECK_APP_REGION: [320, 280, 10, 10],
  CHECK_FRIENDS_REGION: [120, 480, 10, 10],
  OUT_REGION: [400, 1246, 50, 50],
  OUT_IN_FRIENDS_REGION_RIGHT: [800, 1415, 50, 50],
  OUT_IN_FRIENDS_REGION_LEFT: [340, 1415, 50, 50],
  LEFT_THIEF_REGION: [400, 1583, 10, 10],
  LEFT_PUNCH_REGION: [590, 1477, 100, 100],
  RIGHT_THIEF_REGION: [930, 1551, 10, 10],
  RIGHT_PUNCH_REGION: [980, 1477, 100, 100],
  DISMISS_REGION: [450, 1890, 10, 10],
  FOOD_REGION: [850, 1700, 10, 10],
  SPEED_CHECK_REGION: [480, 1569, 10, 10],
  FEED_POSITION: {
    x: 930,
    y: 1960
  },
  TOOL_POSITION: {
    x: 960,
    y: 645
  },
  SPEED_CARD_POSITION: {
    x: 191,
    y: 1450
  },
  CONFIRM_POSITON: {
    x: 720,
    y: 1320

【供大家参考，再次鸣谢作者】

**Comment by baocq2019** [comment]
请问作者下次任务设定重启时间在哪里修改，谢谢。

**Comment by TonyJiangWJ** [comment]
- `core/AntManorRunner.js line:406-408` setUpAutoStart 就是设置几分钟后自动启动的

  ```javascript    
  let sleepTime = _commonFunctions.getSleepTimeAutoCount()
  this.setFloatyInfo(null, sleepTime + '分钟后来检查状况')
  _commonFunctions.setUpAutoStart(sleepTime)
  ```
- 更进阶的重启时间进入`lib/CommonFunction.js line:534`查看
