### ISSUE TITLE
 更新后位置配置出现问题

### ISSUE THREAD

**Issue by williamglasgow** [TonyJiangWJ/Ant-Manor#20]
更新了以后位置配置都变了，都偏高，且修改CustomConfig.js后运行配置可视化没有变化，已退回上个版本
仅做参考

**Comment by dlinkqu** [comment]
有一个水滴屏参数，改成0。

**Comment by TonyJiangWJ** [comment]
运行config.js  修改 `挖孔或水滴刘海偏移量` 改成0即可

**Comment by TonyJiangWJ** [comment]
更新到最新版吧 刘海高度改为自动识别了
