### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by Prophetia086** [TonyJiangWJ/Ant-Manor#21]
根据之前玩儿小鸡的经验，总结了几个规律，可以减少执行次数。

1、喂食后，20-30分钟之间会来一次偷吃的小鸡；
2、只要赶走一次偷吃的小鸡，一直到本次粮食吃完，不会再有小鸡来了；
3、如果30分钟之内没有小鸡来偷吃，那本次就不会有小鸡来了。

所以，是否可以改为，喂食之后，30分钟来检查一次，然后赶走或者揍一顿（配置里面选）；赶走之后，页面会重新计算时间，根据倒计时计算下次来喂食的时间，到时候再执行即可。

按照这个逻辑，每一轮喂食之需要来两次，一次喂、一次赶；就算每次都用加速卡，每次都被偷吃，一天最多只有7-8轮（算上被人提醒后赠送的粮食），就是14次就够了，比现在更简单一些。
而且只要即使喂食，小鸡好像根本不会离家出走，所以其他的逻辑可能大概率用不上。

感谢！

**Comment by TonyJiangWJ** [comment]
现在的逻辑不就是你想的那样吗，只不过是喂食后20分钟后来检查；然后根据循环检测时间来轮询是否有野鸡，有就揍，没有就达到40分钟后停止轮询。然后按实际倒计时时间来执行下一次。
你是第二个按实际已经存在的功能来提需求的了，不是很明白你们是不是没用实际使用过，或者是不是没完全配置准确？

**Comment by Prophetia086** [comment]
> 使用

抱歉，确实是我没搞清楚。

一开始默认是每5分钟检查一次，而且我观察了一下，喂鸡之后，提示5分钟后再来查看情况，5分钟之后查看了情况又提示5分钟之后查看情况，我就以为是每5分钟都来查看情况，并没有根据剩余时间来计算。所以我用的时候都是打走了鸡就手动停止，然后下次喂的时候再启动一次。不知道有40分钟后就不再循环了，而是根据剩余时间来计算。

收到回复之后我改了间隔时间，然后也观察了，确实是40分钟之后就会根据剩余时间计算，还可以配置剩余时间多几分钟再来，避免来了又扑空的情况。

但是我确实没有看到相关的使用说明，比如40分钟就不再检查了。麻烦问问有更详细的说明页面吗？

**Comment by youm1ng** [comment]
> > 使用
> 
> 抱歉，确实是我没搞清楚。
> 
> 一开始默认是每5分钟检查一次，而且我观察了一下，喂鸡之后，提示5分钟后再来查看情况，5分钟之后查看了情况又提示5分钟之后查看情况，我就以为是每5分钟都来查看情况，并没有根据剩余时间来计算。所以我用的时候都是打走了鸡就手动停止，然后下次喂的时候再启动一次。不知道有40分钟后就不再循环了，而是根据剩余时间来计算。
> 
> 收到回复之后我改了间隔时间，然后也观察了，确实是40分钟之后就会根据剩余时间计算，还可以配置剩余时间多几分钟再来，避免来了又扑空的情况。
> 
> 但是我确实没有看到相关的使用说明，比如40分钟就不再检查了。麻烦问问有更详细的说明页面吗？

你需要执行config进行设置，设置轮巡间隔，就是每隔几分钟检测一次是否有小鸡来。
