### ISSUE TITLE
蚂蚁庄园程序故障

### ISSUE THREAD

**Issue by youm1ng** [TonyJiangWJ/Ant-Manor#22]
大概11月10号左右开始，蚂蚁庄园程序检测完“加速卡是否使用成功”后不再进行下一步，也无任何文字提示。去autojs里看，程序自动设置几分钟再来查看，请问是何原因？
错误代码：
11:19:01.929/E: fileName:file:/storage/emulated/0/脚本/Ant-Manor-master/core/AntManorRunner.js line:408 typeof e:object
中间还有很多红色代码
11:19:01.938/E: 执行发生异常TypeError: Cannot read property "0" from undefined 三分钟后重启

**Comment by TonyJiangWJ** [comment]
检查一下你修改过的CustomConfig.js里面是不是少了 COUNT_DOWN_REGION

**Comment by youm1ng** [comment]
是的，已经添加进去了，好用o(￣▽￣)ｄ good
