### ISSUE TITLE
定时功能问题，求助

### ISSUE THREAD

**Issue by baocq2019** [TonyJiangWJ/Ant-Manor#23]
详细调试日志如下

**Comment by baocq2019** [comment]
15：37：17.952/V：开始运行[/storage/emulated/0/脚本/Ant-Manor-master/main.js]
15：37：18.001/V：24使用异步日志
15：37：18.031/V：异常终止的重启任务已存在：[{"m Action"："org.auto js.auto js.action.startup"mLocal"：true， "m Script Path"："/storage/emulated/0/脚本/Ant-Manor-master/ib/prototype/Crash Catcher.js"， "mld"：21} ]
15：37：18.043/V：Is_origin_images null?false.
15：37：18.044/V：图片资源代理创建完毕， 准备替换scope中的images
15：37：18.044/V：图片资源代理替换images完毕
15：37：18.044/D：=====单脚本运行直接清空任务队列二=二二=
15：37：18.050/D：清除数据成功
15：37：18.050/D：======加入任务队列，并关闭重复运行的脚本==二=二
15：37：18.060/V：队列小于等于1不需要去重：null
15：37：18.084/V：当前无任务等待， 直接执行：{"source"："/storage/emulated/0/脚本/Ant-Manor-master/main.js""engine ld"：24}
15：37：18.094/V：设置脚本状态为执行中
15：37：18.164/V：添加运行状态监听器，结束时释放通话状态监听
15：37：18.187/D：使用内置解锁模块
15：37：18.313/D：Baidu OCR当前api Key：0dGhhlf529lp1bB7vdH5vYFe
15：37：18.320/V：转换后配置：{"CHECK_APP_COLOR"："#eb 3619"， "CHECK_FRIENDS_COLOR"："#52adff"， "THIEF_COLOR"："#000000"， "PUNCH_COLOR"："#f 35458"， "OUT_COLOR"："#c27a3f""OUT_IN_FRIENDS_COLOR"："#f4d81d"， "DISMISS_COL OR"："#f9622f"， "FOOD_COLOR"："#ffc fOO"， "SPEEDCHECK_COLOR"："#ffd 000"， "CHECK_APP_REGION"：[310， 303， 20， 20] ， "CHECK_FRIENDS_REGION"：[120， 520， 10， 10] ， "OUT_REGION"：[400， 1350， 25， 25] ，"OUT_IN_FRIENDS_REGION11[800， 1533， 50， 50] ， "OUT IN FRIENDSREGION LEFT"：340， 1533， 50， 50] ， "LEFT_THIEF_REGION"：400， 1600， 50， 50] ， "LEFT_PUNCH_REGION"：[580， 1440， 100， 100] ，"RIGHT_THIEF_REGION"：[800， 1600， 50， 50] ， "RIGHT_PUNCH_REGION"：[1010， 1440， 50， 50] ， "DISMISS_REGION"：[450， 2047， 10， 10] ， "FOOD_REGION"：[860， 1740， 10， 10] ， "SPEEDCHECK_REGION"：[500， 1630， 10， 10] ， "FEED_POSITION"：{"x"：930， "y"：2150} ， "TOOL_POSITION"：{"x"：960， "y"：645} ， "SPEED_CARD_POSITION"：{"x"：190， "y"：1630} ， "CONFIRM_POSITON"：{"x"：800， "y"：1440} ， "SHIT_CHECK_REGION"：[435， 1925， 40， 40] ， "COLLECT_SHIT_CHECK_REGION"：[220， 2000， 80， 40] ， "PICK_SHIT_GRAY_COLOR"："#A6A 6A 6"， "COLLECT_SHIT_GRAY_COLOR"："#838383"}
15：37：18.321/V：通话状态监听功能当前启用状态：true
15：37：18.327/D：====校验无障碍功能======
15：37：18.333/V：当前已启用无障碍功能的服务：com.android.settings/com.android.settings.accessibility.accessibility menu.AccessibilityMenuService：org.autojs.autojs/com.stardust.auto js.core.accessibility.Accessibility Service
15：37：18.334/D：---前置校验完成；启动系统--->
15：37：18.335/D：版本信息：v1.0.4.10.2node ld：MDc6UmVsZWFzZTI1Mjc0MzQx
15：37：18.335/D：Auto JS version ：4.1.1 Alpha 2
15：37：18.336/D：device info：Xiao mi raphael 10
15：37：18.336/D：设备分辨率：[1080，2340]
15：37：18.337/D：=====解锁======
15：37：18.338/D：需要重新锁定屏幕
15：37：22.342/V：保存是否需要重新锁屏：true
15：37：22.349/D：解锁成功
15：37：22.562/V：开始申请截图权限
15：37：22.564/V：已存储截图权限申请标记
15：37：22.567/V：已开启弹窗监测线程
15：37：22.770/V：截图权限申请结果：true×
15：37：23.012/D：请求截屏权限成功
15：37：23.012/V：action执行结束：true耗时：661ms
15：37：23.012/V：等待悬浮窗初始化
15：37：23.474/V：悬浮窗初始化成功
15：37：23.475/V：不再展示延迟对话框， screen_locked
15：37：23.476/：即将开始，按音量下键延迟五分钟执行
15：37：24.961/V：获取截图耗时：34ms
15：37：24.988/V：设置悬浮窗位置：null内容：进入个人鸡鸡页面成功
15：37：24.994/V：设置悬浮窗位置：null内容：打开APP成:功!
15：37：25.478/V：after set Max Listeners
15：37：25.484/V：after observe Key
15：37：25.487/V：after set Once KeyDown
15：37：26.068/V：获取截图耗时：43ms
15：37：26.629/V：获取截图耗时：38ms
15：37：26.651/V：转换region位置：[400， 1600， 50， 50]
15：37：26.655/V：设置悬浮窗位置：{"x"：425，"y"：1625}内容：左边没野鸡
15：37：27.201/V：获取截图耗时：38ms
15：37：27.220/V：转换region位置：[800， 1600， 50， 50]
15：37：27.221/V：设置悬浮窗位置：{"x"：825，"y"：1625}内容：右边没野鸡
15：37：28.228/V：设置悬浮窗位置：null内容：没有野鸡哦
15：37：28.777/V：获取截图耗时：43ms
15：37：28.792/V：设置悬浮窗位置：{"x"：860.0，"y"：1740.0}内容：小鸡有饭吃哦
15：37：31.341/V：获取截图耗时：42ms
15：37：31.363/V：设置悬浮窗位置：{"x"：500.0，"y"：1630.0}内容：加速卡使用成功
15：37：32.901/V：action执行结束：true耗时：30ms
15：37：32.903/V：获取截图耗时：30ms
15：37：32.904/V：region：undefined
15：37：32.907/E：fileName：file：/storage/emulated/0/脚本/Ant-Manor-master/core/AntMan or Runner.js Line：407typeofe：object
15：37：32.912/E：Can not read property"O"from undefined:or q.mozilla.javascript.Ecma Error：TypeError：


Can not read property"O"from undefined(file：/storage/emulated/0/脚本/Ant-Manor-master/core/AntMan or Runner.js#407)
at
org.mozilla.javascript.Script Runtime.construct Error(Script Runtime .java： 4142)
at
org.mozilla.javascript.Script Runtime.construct Error(Script Runtime .java： 4120)
at
org.mozilla.javascript.Script Runtime.typeError(Script Run time .java： 4153)
at
org.mozilla.javascript.Script Runtime.typeError 2(ScriptRuntime .java： 4172)
at
org.mozilla.javascript.Script Runtime.undef Read Error(Script Runtime .java： 4184)
at
org.mozilla.javascript.Script Runtime.getObject Index(Script Runtime .java： 1595)
at
org.mozilla.javascript.Interpreter.do Get Elem(Interpreter.java： 2225)
at
org.mozilla.javascript.Interpreter.interpret Loop(Inter preter.java： 1264)
at script(file：/storage/emulated/0/脚本/Ant-Manor-master/core/AntMan or Runner .js：407)
at script(file：/storage/emulated/0/脚本/Ant-Manor-master/core/AntMan or Runner .js：329)
at script(file：/storage/emulated/0/脚本/Ant-Manor-master/core/AntMan or Runner .js：452)
at script.main Exec(/storage/emulated/0/脚本/An t-Manor-master/main.js： 128)
at script(/storage/emulated/0/脚本/Ant-Manor-master/main.js： 136)
at
org.mozilla.javascript.Interpreter.interpret(Interpreter.java： 815)
at
org.mozilla.javascript.Interpreted Function.call(Interpreted Function .java： 109)
at
org.mozilla.javascript.Context Factory.do Top Call(Context Factory .java： 399)
at
org.mozilla.javascript.Script Runtime.do Top Call(Script Run time .java： 3452)
at
org.mozilla.javascript.Interpreted Function.exec(Inter pre ted Function .java： 120)
at
com.stardust.auto js.engine.Rhino JavaScript Engine.doEx ecution(Rhino JavaScript Engine.kt：79)
at
com.stardust.auto js.engine.JavaScript Engine.execute(JavaScript Engine.java：20)
at
com.stardust.auto js.engine.Loop Based JavaScript Engine.access$001(Loop Based JavaScript Engine.java：21)
at
com.stardust.auto js.engine.Loop Based JavaScript Engine.lambda$execute$0(Loop Based JavaScript Engine.java：46)
at com.stardust.auto js.engine.-$
$Lambda$Loop Based JavaScript Engine$ffo qW CRm 35mszUY9IWNMZL1Mntg.run(Unknown Source：6)
at android.os.Handler.handle Callback(Handler.java：914)
at android.os.Handler.dispatch Message(Handler.java：100)
at and roid.os. Looper.loop(Looper.java： 238)
at
com.stardust.auto js.engine.Loop Based JavaScript Engin

e.execute(Loop Based JavaScript Engine.java：65)
at
com.stardust.auto js.engine.Loop Based JavaScript Engine.execute(Loop Based JavaScript Engine.java：38)
at
com.stardust.auto js.execution.Looped Based JavaScriptExecution.do Execution(Looped Based JavaScript Execution.java：42)
at
com.stardust.auto js.execution.Runnable Script Execut ion.execute(Runnable Script Execution.java：43)
at
com.stardust.auto js.execution.Runnable Script Execut ion.execute(Runnable Script Execution.java：37)
at
com.stardust.auto js.execution.Runnable Script Execut ion.run(Runnable Script Execution.java：31)
at java.lang. Thread .run(Thread.java： 919)
15：37：32.913/E：执行发生异常TypeError：Can not readproperty"O"from undefined三分钟后重启
15：37：32.918/V：撤销自动任务：{"mDelay"：0， "m Interval"：0， "m Loop Times"：1， "m Millis"：1606203437784， "m Scheduled"：true， "m Script Path"："/storage/emulated/O/脚本/Ant-Manor-master/main.js"， "mTime Flag"：0， "mld"：346}
15：37：32.922/：预订[3]分钟后的任务，时间戳：1606203632921
15：37：33.008/V：定时任务预定成功：347
15：37：33.015/D：是否需要重新锁定屏幕：true
15：37：33.017/V：重新锁定屏幕
15：37：33.370/V：保存是否需要重新锁屏：false
15：37：33.375/V：获取运行中任务信息：{"source"："/storage/emulated/0/脚本/Ant-Manor-master/main.js"， "engine ld"：24， "timeout"：16062043380°超时剩余时间：885秒

15：37：33.377/V：准备移除运行中任务
15：37：33.407/V：队列小于等于1不需要去重：null
15：37：33.008/V：定时任务预定成功：347
15：37：33.015/D：是否需要重新锁定屏幕：true
15：37：33.017/V：重新锁定屏幕
15：37：33.370/V：保存是否需要重新锁屏：false
15：37：33.375/V：获取运行中任务信息：{"source"："/storage/emulated/O/脚本/Ant-Manor-master/main.js"，"engine ld"：24， "timeout"：1606204338085} 超时剩余时间：885秒
15：37：33.377/V：准备移除运行中任务
15：37：33.407/V：队列小于等于1不需要去重：null
15：37：33.417/V：无任务等待中
15：37：33.426/V：设置脚本状态为执行完毕
15：37：33.430/V：[/storage/emulated/0/脚本/Ant-Manor-master/main.js] 运行结束， 用时15.478000秒
15：37：33.595/V：脚本已经中止执行，执行生命周期回调
15：37：33.598/V：执行生命周期回调：resource Monitor
15：37：33.601/I：脚本执行结束，释放图片资源
15：37：33.603/V：释放图片，总数：7
15：37：33.609/V：同步释放所有图片，耗时3
15：37：33.611/V：解除图像资源代理
15：37：33.614/V：执行生命周期回调：call State
15：37：33.615/I：脚本执行结束，移除通话状态监听
15：37：33.617/V：通话状态监听功能当前启用状态：true
15：37：33.619/V：执行生命周期回调：main
15：37：33.620/W：无任务在运行中，不可移除
15：37：33.622/V：保存是否需要重新锁屏：false
15：37：33.636/V：lifecycle Deamon线程池关闭：true
15：37：33.638/V：24写入日志到文件耗时：14ms
15：37：33.639/V：24切换缓冲区，将缓冲区内容全部写入日志
15：37：33.640/V：24写入日志到文件耗时：1ms
15：37：33.643/W：24脚本执行结束，日志文件写入线程关闭
15：37：33.643/V：24日志入队总耗时：25ms写耗时：15ms备份日志文件总耗时：0ms
15：37：33.644/V：24日志线程池关闭：true

**Comment by TonyJiangWJ** [comment]
在你扩展的CustomConfig.js里面加上倒计时识别区域的配置，具体位置自己修改一下
```
  //....
  COUNT_DOWN_REGION: [810, 1600, 160, 55],          // 倒计时区域
  //....
```

**Comment by TonyJiangWJ** [comment]
已更新新版本，可以通过可视化配置工具直接调整相应内容，不再需要扩展CustomConfig.js
