### ISSUE TITLE
可视化配置工具最下面四个无法配置

### ISSUE THREAD

**Issue by zhufscug** [TonyJiangWJ/Ant-Manor#24]
可视化配置工具最下面四个喂食，道具，加速卡，确认的位置信息配置之后，返回再次进入，还是以前的值

另外是否能告知这个可视化配置是配置到本地哪个文件里面去了吗

**Comment by zhufscug** [comment]
我特意看了下可视化配置工具并修改了一个参数之后，在Ant-Manor目录下所有文件的系统时间都没有修改，说明这个配置文件并没有修改保存到这个目录下面的任何文件中，不知道这个配置工具最终是写到哪个文件中去的

**Comment by TonyJiangWJ** [comment]
更新到最新版没有，新版本已经修复，配置写入到内置存储中了，不在文件中。
