### ISSUE TITLE
代码有个bug

### ISSUE THREAD

**Issue by Prophetia086** [TonyJiangWJ/Ant-Manor#25]
最近使用的时候发现一个bug，就是小鸡吃饭还剩1小时以内的时候，会无法正确设定下次运行时间，看了代码，找到了问题

AntManorRunner这个js里面，342到347行，判断识别文本，当结果为分+秒时，没有定义regexResult的值，导致报错。
我自己在else if里面加上一行就没问题了

之前改过，但是一升级又被覆盖了，所以提出来

前后见截图
![Screenshot_20210110-120117_Autojs](https://user-images.githubusercontent.com/73395827/104114168-4b377180-533c-11eb-9cbf-72a6ab11b0e3.png)
![Screenshot_20210110-120117_Autojs](https://user-images.githubusercontent.com/73395827/104114173-538fac80-533c-11eb-9e2a-5ee1690d9b61.png)

**Comment by Prophetia086** [comment]
另外，请问怎么能支持分身呢？我有两个账号，我想把auto.js和支付宝都分身，但是发现两个auto.js都会调用主支付宝，不能调用支付宝分身。请问有办法吗？谢谢

**Comment by Prophetia086** [comment]
才发现两张截图传成同一张了，补发
![Screenshot_20210110-120302_Autojs](https://user-images.githubusercontent.com/73395827/104116327-847adc00-5352-11eb-9675-731e1948afc7.png)

**Comment by TonyJiangWJ** [comment]
下次更新修复此问题。分身的话暂时么有办法
