### ISSUE TITLE
关于分辨率offset

### ISSUE THREAD

**Issue by 5high** [TonyJiangWJ/Ant-Manor#26]
配置文件中的offset能否给个事例，看了看readme，里面未提及offset的问题，想自行修改分辨率感觉有些无从下手。

是否offset为分辨率格式 ？ 例如 1280*720 ？ 还是x,10,y10? 能否在readme中增加这个示例

**Comment by TonyJiangWJ** [comment]
更新最新版 通过可视化配置来修改配置 不需要再创建自定义配置的文件了
