### ISSUE TITLE
请问大佬们小鸡捡屎失败怎么搞

### ISSUE THREAD

**Issue by hdb66** [TonyJiangWJ/Ant-Manor#27]
![1614830621(1)](https://user-images.githubusercontent.com/78214803/109909913-e831dd80-7ce1-11eb-948c-aff0d91c86c2.png)
脚本运行的时候有提示可以捡屎，到收集的时候就直接退出了

**Comment by TonyJiangWJ** [comment]
截图日志中的是倒计时识别区域不正确，捡屎的话也是一样的 需要配置一下
- 运行 `可视化配置.js` 切换到校验区域配置，调整相应配置项 可以实时查看区域信息，也可以截图蚂蚁庄园图片（命名为蚂蚁庄园截图.jpg替换到test目录下即可）作为背景图方便实时调整，或者隐藏背景图到蚂蚁庄园首页查看具体位置信息。颜色值基本不需要修改

**Comment by hdb66** [comment]
您好！配置我调过的，捡的区域也在里面的。运行之后到捡的时候就直接退出了








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TonyJiangWJ/Ant-Manor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 中午1:22
收件人:&nbsp;"TonyJiangWJ/Ant-Manor"<Ant-Manor@noreply.github.com&gt;;
抄送:&nbsp;"?????"<895206760@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TonyJiangWJ/Ant-Manor] 请问大佬们小鸡捡屎失败怎么搞 (#27)





 
截图日志中的是倒计时识别区域不正确，捡屎的话也是一样的 需要配置一下
  
运行 可视化配置.js 切换到校验区域配置，调整相应配置项 可以实时查看区域信息，也可以截图蚂蚁庄园图片（命名为蚂蚁庄园截图.jpg替换到test目录下即可）作为背景图方便实时调整，或者隐藏背景图到蚂蚁庄园首页查看具体位置信息。颜色值基本不需要修改

**Comment by TonyJiangWJ** [comment]
那就提供一下完整的日志吧  你截图里面仅仅展示了倒计时的错误

**Comment by hdb66** [comment]
你好，附件是所有的日志，请查看，谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TonyJiangWJ/Ant-Manor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 下午3:09
收件人:&nbsp;"TonyJiangWJ/Ant-Manor"<Ant-Manor@noreply.github.com&gt;;
抄送:&nbsp;"?????"<895206760@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TonyJiangWJ/Ant-Manor] 请问大佬们小鸡捡屎失败怎么搞 (#27)





 
那就提供一下完整的日志吧  你截图里面仅仅展示了倒计时的错误

**Comment by TonyJiangWJ** [comment]
并没有收到附件，可能是github邮件回复的机制问题无法正确传递附件，你可以直接发送到我的邮箱 tonyjiangwj@gmail.com

**Comment by hdb66** [comment]
邮件已发，请问有收到吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TonyJiangWJ/Ant-Manor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 下午3:19
收件人:&nbsp;"TonyJiangWJ/Ant-Manor"<Ant-Manor@noreply.github.com&gt;;
抄送:&nbsp;"?????"<895206760@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TonyJiangWJ/Ant-Manor] 请问大佬们小鸡捡屎失败怎么搞 (#27)





 
并没有收到附件，可能是github邮件回复的机制问题无法正确传递附件，你可以直接发送到我的邮箱 tonyjiangwj@gmail.com

**Comment by TonyJiangWJ** [comment]
有的，我看一下

**Comment by TonyJiangWJ** [comment]
可否再截图一张蚂蚁庄园的界面

**Comment by hdb66** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TonyJiangWJ/Ant-Manor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 下午3:38
收件人:&nbsp;"TonyJiangWJ/Ant-Manor"<Ant-Manor@noreply.github.com&gt;;
抄送:&nbsp;"?????"<895206760@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TonyJiangWJ/Ant-Manor] 请问大佬们小鸡捡屎失败怎么搞 (#27)





 
可否再截图一张蚂蚁庄园的界面

**Comment by TonyJiangWJ** [comment]
相关配置区域你参考一下，我觉得是你有几个配错了

![Screenshot_2021-03-05-15-45-13-939_com eg android AlipayGphone](https://user-images.githubusercontent.com/11325805/110083614-e5121c80-7dc9-11eb-817d-183cea0f6404.jpg)
![Screenshot_2021-03-05-15-45-19-794_com eg android AlipayGphone](https://user-images.githubusercontent.com/11325805/110083641-eb07fd80-7dc9-11eb-8e79-86f81dcdcd51.jpg)

**Comment by TonyJiangWJ** [comment]
重点关注配置中的这几项 `OCR校验倒计时的区域，需要精确框选` , `校验是否可以捡屎的区域` , `校验执行捡屎的区域`
