### ISSUE TITLE
你好，可视化配置打开失败

### ISSUE THREAD

**Issue by y154541000** [TonyJiangWJ/Ant-Manor#28]
autojs4.0

**Comment by y154541000** [comment]
![Uploading Screenshot_20210316-200530.jpg…]()

**Comment by y154541000** [comment]
![Uploading Screenshot_20210316-200530.jpg…]()

**Comment by y154541000** [comment]
报错failed to define class

**Comment by TonyJiangWJ** [comment]
下载安装 [AutoJs 4.1.1 alpha2](http://47.110.40.234/autojs/autojs-4.1.1-alpha2.apk) or [AutoJS Modify](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AutoJS.Modify.latest.apk)
