### ISSUE TITLE
你好，总是显示加速卡使用失败

### ISSUE THREAD

**Issue by xukellp** [TonyJiangWJ/Ant-Manor#29]
你好，总是显示加速卡使用失败。已经开启了使用加速卡，道具按钮等等的位置也对

**Comment by hdb66** [comment]
应该是颜色错了，改成  #f8c838   试试看

**Comment by hdb66** [comment]
![1617867465(1)](https://user-images.githubusercontent.com/78214803/113987085-8fc1a300-9880-11eb-9677-8b6c4b948f33.png)

我是选择这个区域的

**Comment by TonyJiangWJ** [comment]
更新最新版 然后重置一下默认配置，再微调一下位置就行了 上一版本颜色不适配现在的蚂蚁庄园界面
