### ISSUE TITLE
近期使用问题汇总

### ISSUE THREAD

**Issue by baocq2019** [TonyJiangWJ/Ant-Manor#3]
机型：Redmi K20 pro
系统：MIUI 11.0.4稳定版
AutoJS：4.1.1alpha2

分辨率2340×1080，修改部分参数如下

const default_chick_config = {
  CHECK_APP_COLOR: '#f13414',
  CHECK_FRIENDS_COLOR: '#52adff',
  THIEF_COLOR: '#000000',
  PUNCH_COLOR: '#f35458',
  OUT_COLOR: '#c27a3f',
  OUT_IN_FRIENDS_COLOR: '#f4d81d',
  DISMISS_COLOR: '#f9622f',
  FOOD_COLOR: '#ffcf00',
  SPEED_CHECK_COLOR: '#ffd000',

  CHECK_APP_REGION: [320, 280, 10, 10],
  CHECK_FRIENDS_REGION: [120, 480, 10, 10],
  OUT_REGION: [400, 1246, 50, 50],
  OUT_IN_FRIENDS_REGION_RIGHT: [800, 1415, 50, 50],
  OUT_IN_FRIENDS_REGION_LEFT: [340, 1415, 50, 50],
  LEFT_THIEF_REGION: [400, 1583, 10, 10],
  LEFT_PUNCH_REGION: [590, 1477, 100, 100],
  RIGHT_THIEF_REGION: [930, 1583, 10, 10],
  RIGHT_PUNCH_REGION: [980, 1477, 100, 100],
  DISMISS_REGION: [450, 1890, 10, 10],
  FOOD_REGION: [850, 1700, 10, 10],
  SPEED_CHECK_REGION: [480, 1569, 10, 10],
  FEED_POSITION: {
    x: 930,
    y: 1960
  },
  TOOL_POSITION: {
    x: 960,
    y: 645
  },
  SPEED_CARD_POSITION: {
    x: 191,
    y: 1450
  },
  CONFIRM_POSITON: {
    x: 720,
    y: 1320
  }

正常使用过程中，出现问题日志如下
06:19:21.934/E:Error:Can’t resolve relative module ID”./lib/RuningQueueDispatcher.js”when require() is used outside of a module (file:///android_asset/modules/jvm-npm.js#89)
Error:Can’t resolve relative module ID”./lib/RuningQueueDispatcher.js”when require() is used outside of a module at Require (file:///android_asset/modules/jvm-npm.js:89:0) at storage/emulated/0/脚本/sAnt-Manor-master/main.js2:0

然后界面跳转到无障碍设置画面，打开检查autojs仍然开启无障碍权限，但不能运行脚本，重启后，问题解决，但隔一段时间（约1.2天）后问题又重复出现。想请问是否为autojs版本问题。

另外想请问作者在Commonfunction.js中的脚本下一次设定时间，如何修改，目前来看比预期值晚4分钟，想要减少4分钟如何修改

**Comment by baocq2019** [comment]
重启手机，才能解决以上问题，前段时间曾出现过类似情况，但转换为版本4.1.0alpha5后，情况稳定许多，后又因为蚂蚁森林脚本需要更新到4.1.1alpha2，总体来说使用正常，但还是会出现以上情况。需要每隔一两天重启手机。

**Comment by TonyJiangWJ** [comment]
- 延迟时间是五分钟，具体如下
```javascript
   // line: 550-554 fullTime + 5 这个五分钟的窗口时间，你可以改小
    } else if (returnVal >= 300 || passedTime <= fullTime && passedTime >= 40) {
      // 揍过鸡后会设置为300 此时重新计算具体时间
      // or
      // 经过了超过40分钟 而且此时没有野鸡来 开始睡眠更久不再检测小鸡
      returnVal = parseInt(fullTime + 5 - passedTime)
```
- 报错问题我没有遇到一直用的很稳定 所以也很久没有去更新，今晚增加了图形化界面 总体功能上没有什么变化
