### ISSUE TITLE
用了AntiDetect喂小鸡代码有点异常，经常识别倒计时识别出来负的

### ISSUE THREAD

**Issue by TonyJiangWJ** [TonyJiangWJ/Ant-Manor#32]
另外，用了AntiDetect喂小鸡代码有点异常，经常识别倒计时识别出来负的，然后就一分钟以后再运行一次。我还没整明白是哪里不对。

_Originally posted by @williamglasgow in https://github.com/TonyJiangWJ/Ant-Forest/issues/111#issuecomment-875377171_

**Comment by TonyJiangWJ** [comment]
这个需要看一下截图的区域信息是否准确，你提供一下运行的日志我看看

**Comment by williamglasgow** [comment]
我好像发现原因了，现在小鸡的进食倒计时位置会变，随着食盆里的粮变少变矮也会跟着降低。
![1](https://user-images.githubusercontent.com/58156677/124724022-2fed9d80-df3e-11eb-89f0-fb45647619fe.jpg)

**Comment by TonyJiangWJ** [comment]
那可以把识别框的高度设置的大一点 范围大一点没关系的 能识别出来

**Comment by williamglasgow** [comment]
可以的，我把高度调大了，识别没问题了。谢谢大佬！
