### ISSUE TITLE
小米12pro找到偷吃小鸡后无法点击

### ISSUE THREAD

**Issue by hdb66** [TonyJiangWJ/Ant-Manor#34]
[蚂蚁庄园运行日志.txt](https://github.com/TonyJiangWJ/Ant-Manor/files/7939085/default.txt)
Hello，小米12pro使用中遇到以下问题，麻烦帮忙看一下如何解决，多谢！
找到偷吃小鸡后无法点击，手动点击后，能找到拳头同时也无法点击，等待时间过后直接跳过了

**Comment by Prophetia086** [comment]
三星S10+遇到同样的问题，应该是升级android12导致的，升级前没问提
隔壁蚂蚁森林由针对Android12问题的解决方案，希望这里也有一个
