### ISSUE TITLE
饲料袋已满会卡住

### ISSUE THREAD

**Issue by heham** [TonyJiangWJ/Ant-Manor#36]
饲料袋已满会卡住

**Comment by TonyJiangWJ** [comment]
卡住？但是不影响后续流程吧 你是怎么实现用脚本还能让饲料袋满的。。从不用加速卡的吗

**Comment by heham** [comment]
会影响，看着他在那不停的点击弹窗下面的按钮但是按不到，我的号没弄过，简单测试一下就满了然后就卡住了

**Comment by TonyJiangWJ** [comment]
失败了脚本过几分钟重试就行了呀
