### ISSUE TITLE
大神，蚂蚁新村自动摆摊怎么弄？readme.md里找不到教程

### ISSUE THREAD

**Issue by guojiananGitHub** [TonyJiangWJ/Ant-Manor#38]
如题所述

**Comment by TonyJiangWJ** [comment]
首先运行 可视化配置 配置一下 自动摆摊需要识别的图片 然后运行 `unit/蚂蚁新村自动摆摊.js`
这种新增功能一般都在写release里面 readme懒得写。。
https://github.com/TonyJiangWJ/Ant-Manor/releases/tag/v1.2.1
