### ISSUE TITLE
蚂蚁新村会卡死

### ISSUE THREAD

**Issue by xukellp** [TonyJiangWJ/Ant-Manor#39]

**Comment by xukellp** [comment]
卡在准备查找是否有空位，然后就卡死，手机有时也会死机

**Comment by xukellp** [comment]
在自动摆摊环节会卡死

**Comment by xukellp** [comment]
已安装最新修改版autojs，另附日志，是20220609-2108开始的任务，之后很快卡死。然后重启
[log-verboses.log](https://github.com/TonyJiangWJ/Ant-Manor/files/8870689/log-verboses.log)

**Comment by TonyJiangWJ** [comment]
看不出原因 你暂时不要用了
