### ISSUE TITLE
可能是支付宝版本升级，进入蚂蚁庄园后页面会左右飘

### ISSUE THREAD

**Issue by zhufscug** [TonyJiangWJ/Ant-Manor#42]
如题，小鸡在图中的位置有可能不在最中央，有可能到最左边或者最右边，导致无法找图找色，脚本几乎无法使用

**Comment by TonyJiangWJ** [comment]
目前使用正常 没有出现你说的这种情况 如果你那边确实随机的不在正中间 那确实没办法

**Comment by zhufscug** [comment]
现在蚂蚁庄园，小鸡后面的背景更宽了，所以左右滑动蚂蚁庄园的页面的话，小鸡相对位置会变化，不一定在屏幕中间了，我根据日志排查，发现是  日志这一步    “**获取截图失败，尝试滑动界面，触发渲染**”  导致了小鸡的位置变化

**Comment by TonyJiangWJ** [comment]
无法获取截图 你可以尝试修改 截图超时时间 默认500ms 自己调试增加到合适的值  或者直接关闭异步等待截图
