### ISSUE TITLE
领饲料的时候一直死循环

### ISSUE THREAD

**Issue by zhufscug** [TonyJiangWJ/Ant-Manor#44]
如题，没完没了的执行，麻烦作者看一下哈
![QQ图片20221122165441](https://user-images.githubusercontent.com/76509332/203269711-f898d982-db1f-460d-bc4a-a05e1670d061.jpg)

**Comment by TonyJiangWJ** [comment]
是最新版吗 不是的话更新一下 记得一个月前解决了的
