### ISSUE TITLE
看日志执行耗时有两个步骤非常长

### ISSUE THREAD

**Issue by zhufscug** [TonyJiangWJ/Ant-Manor#45]
如图，中间间隔了5分钟，不知道是什么情况

![QQ图片20221128110527](https://user-images.githubusercontent.com/76509332/204182979-93926ae6-8199-4025-9454-ec65638df4c1.jpg)

**Comment by TonyJiangWJ** [comment]
看一下logs/log-verboses.log

**Comment by zhufscug** [comment]
![QQ图片20221130161404](https://user-images.githubusercontent.com/76509332/204742782-3c87b9e9-9f16-49fa-9104-44448dd17083.jpg)



还是这个问题，不过又换了一个地方，这个步骤耗时4分钟，不知道啥情况

**Comment by TonyJiangWJ** [comment]
更新最新版试试

**Comment by TonyJiangWJ** [comment]
更新最新版试试

**Comment by zhufscug** [comment]
![QQ图片20221212150549](https://user-images.githubusercontent.com/76509332/206982018-a25de892-43d5-49c6-a0b8-6dc2e922c933.jpg)


还是有步骤耗时较长，脚本14:52开始跑了，耗时到14:59 日志出来run resolver
不知道中间经历了什么

**Comment by zhufscug** [comment]
以上脚本是刚更新最新版跑的结果

**Comment by TonyJiangWJ** [comment]
另外可以更新最新版本的试一下：https://github.com/TonyJiangWJ/Auto.js/releases

**Comment by zhufscug** [comment]
下午这个就是更新最新版本跑的结果

**Comment by TonyJiangWJ** [comment]
那不知道了 无法解决
