### ISSUE TITLE
怎么找不到 AutoJs Modify 了

### ISSUE THREAD

**Issue by CuteLicense** [TonyJiangWJ/Ant-Manor#47]
下载安装 [AutoJs Modify](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AutoJS.Modify.latest.apk) 
链接无效了，能不能再放出来一下，谢谢！

**Comment by TonyJiangWJ** [comment]
https://github.com/TonyJiangWJ/Ant-Forest/releases/download/v1.1.1.4/AutoJS.modify.latest.apk

**Comment by CuteLicense** [comment]
感谢
