### ISSUE TITLE
AutoJs Modify 能否在管理中增加按照名称进行排序？

### ISSUE THREAD

**Issue by lchongxiu** [TonyJiangWJ/Ant-Manor#48]
AutoJs Modify 默认是按照时间先后顺序进行排序，但如果有多条任务在列表中，很难找到自己要的任务，但如果能按照名称排序就可以很容易找到自己要的程序，顾建议在管理中增加按照名称进行排序。

**Comment by TonyJiangWJ** [comment]
不好意思，这个修改版不再维护了。
