### ISSUE TITLE
领饲料那个配置问题

### ISSUE THREAD

**Issue by zhufscug** [TonyJiangWJ/Ant-Manor#49]
明明配置好好的，过一段时间就失效了，没法自动领，要重新配置，遇到好几次了，这个配置是一个图片，

能不能去掉领饲料按钮的图片配置模式，改成基于坐标的方式直接点击呀

**Comment by TonyJiangWJ** [comment]
你是不是自己开了动态分辨率什么的。这个图片并不会变化，除非有新的活动导致图标变化，否则不会找不到，你如果需要坐标点击，可以自己看代码进行修改。如果你开了动态分辨率，一样还是用不了的
