### ISSUE TITLE
怎么使用？

### ISSUE THREAD

**Issue by lh948** [TonyJiangWJ/Ant-Manor#6]
这个怎么用？有教程吗？

**Comment by TonyJiangWJ** [comment]
- 下载安装 [AutoJs 4.1.1 alpha2 下载](https://www.dropbox.com/s/pe3w53k0fugo1fa/Autojs%204.1.1%20Alpha2.apk?dl=0) 之后把整个脚本项目放进 **"/sdcard/脚本/"** 文件夹下面。打开软件后下拉刷新，然后运行项目或者 main 即可。
- 不同分辨率手机不能完全适配需要自己修改相关配置，可以参考指定ISSUE
