### ISSUE TITLE
config.js无法运行

### ISSUE THREAD

**Issue by whu-lisan** [TonyJiangWJ/Ant-Manor#9]
每次运行config.js都提示请运行config.js输入设备宽高
![错误1](https://user-images.githubusercontent.com/35948100/80936067-1a448b80-8e02-11ea-9dc6-d6b73f94ed14.jpg)
![IMG_20200504_122243](https://user-images.githubusercontent.com/35948100/80936098-3d6f3b00-8e02-11ea-957a-0d66621883f2.jpg)

**Comment by TonyJiangWJ** [comment]
你所使用的AutoJS版本是什么，可能软件版本问题，语法不支持

**Comment by TonyJiangWJ** [comment]
更新最新版即可
